spring:
  application:
    name: Order-Service

  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: c##micro
    password: micro
  config:
    import: optional:configserver:http://localhost:8888  # Makes the Config Server optional
  #cloud:
   # config:
     # uri: http://localhost:8888  # Ensure this is correct
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
server:
     port: 8083
     
#eureka:
   #instance:
        #client:
         #  serverUrl: defaultZone=http://localhost:8761/eureka/